"""Domain entities and value objects."""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

from lir_agent.domain.case_intake import CaseReport


class Lane(StrEnum):
    """Where a turn or a case goes next. Decided by the policy engine, never by the LLM."""

    # Turn lanes
    PROCEED = "proceed"
    CLARIFY = "clarify"
    OUT_OF_SCOPE = "out_of_scope"
    # The customer rejects an explanation: they may approve a dispute (human in the loop).
    REVIEW = "review"
    # Case lanes
    EXPLAIN = "explain"
    DISPUTE = "dispute"
    PROPOSE = "propose"
    # Both
    ESCALATE = "escalate"


class _Frozen(BaseModel):
    model_config = ConfigDict(frozen=True)


class Customer(_Frozen):
    """A bank customer. Identity documents, contact data and financials are not modeled."""

    customer_id: str
    first_name: str | None = None
    country: str | None = None
    city: str | None = None
    segment: str | None = None
    customer_status: str | None = None
    registration_date: datetime | None = None
    accepts_marketing: bool | None = None


class Transaction(_Frozen):
    """A customer's transaction. `is_fraud` is deliberately absent: it is an evaluation label."""

    transaction_id: str
    transaction_date: datetime
    product_id: str | None = None
    transaction_type: str | None = None
    transaction_category: str | None = None
    amount: float | None = None
    currency: str | None = None
    amount_usd: float | None = None
    channel: str | None = None
    merchant_name: str | None = None
    merchant_category: str | None = None
    transaction_country: str | None = None
    transaction_city: str | None = None
    transaction_status: str | None = None
    fraud_score: float | None = None


class Outcome(_Frozen):
    """The lane chosen by a policy rule, with the rule and policy version."""

    lane: Lane
    rule_id: str
    reason: str
    policy_version: str


class Evidence(_Frozen):
    """Verifiable facts about one transaction, computed in code (never by a model)."""

    transaction_id: str
    date: datetime
    amount: float | None
    currency: str | None
    amount_usd: float | None
    merchant_name: str | None
    merchant_category: str | None
    status: str | None
    transaction_type: str | None
    channel: str | None
    merchant_prior_count: int
    merchant_last_seen: datetime | None
    duplicate_of: list[str]
    transaction_country: str | None
    customer_country: str | None
    foreign: bool
    # False when either country is missing or unknown: `foreign` cannot be trusted then.
    country_resolved: bool
    fraud_score: float | None

    @property
    def has_duplicate(self) -> bool:
        """Whether the same merchant charged the same amount within the window."""
        return bool(self.duplicate_of)

    def facts(self) -> dict:
        """Flat view evaluated by the policy engine."""
        return {**self.model_dump(), "has_duplicate": self.has_duplicate}


class DisputeCase(_Frozen):
    """A dispute opened in the case service."""

    case_id: str
    customer_id: str
    transaction_id: str
    reason: str
    status: str
    created_at: datetime


class HandoffPacket(_Frozen):
    """What a human reviewer receives when a case is handed off.

    Request, verified facts, actions, evidence and open questions (Bases §3). Facts come
    from session state, not from model prose.
    """

    handoff_id: str
    created_at: datetime
    customer_id: str
    customer_request: str | None
    turn_outcome: Outcome | None
    case_outcome: Outcome | None
    verified_evidence: list[Evidence] = Field(default_factory=list)
    actions_taken: list[dict] = Field(default_factory=list)
    decisions: dict = Field(default_factory=dict)
    open_questions: list[str] = Field(default_factory=list)
    model_summary: str | None = Field(
        default=None, description="Generated by the LLM; not a verified fact."
    )
    case_report: CaseReport | None = Field(
        default=None, description="What the customer reported in the web form."
    )
